# See https://docs.gitlab.com/ee/ci/yaml/index.html for all available options

image: node:latest

stages:
  - build
  - container

before_script:
  - echo "Before script section"
  # - echo "For example you might run an update here or install a build dependency"
  # - echo "Or perhaps you might print out some debugging details"

after_script:
  - echo "After script section"
  # - echo "For example you might do some cleanup here"

build pdf-service:
  stage: build
  script:
    - bash ./build/scripts/prepare-build.sh
    - bash ./build/scripts/build-pdf-service.sh
  artifacts:
    name: "pdf-service"
    paths:
      - "server/pdf-service/dist"
    expire_in: "7 days"

build tpl-service:
  stage: build
  script:
    - bash ./build/scripts/prepare-build.sh
    - bash ./build/scripts/build-tpl-service.sh
  artifacts:
    name: "tpl-service"
    paths:
      - "server/tpl-service/dist"
    expire_in: "7 days"

build web-designer:
  stage: build
  script:
    - bash ./build/scripts/prepare-build.sh
    - bash ./build/scripts/build-web-designer.sh
  artifacts:
    name: "web-designer"
    paths:
      - "web/designer/www-prod"
    expire_in: "7 days"

build web-print:
  stage: build
  script:
    - bash ./build/scripts/prepare-build.sh
    - bash ./build/scripts/build-web-print.sh
  artifacts:
    name: "web-print"
    paths:
      - "web/print/www-prod"
    expire_in: "7 days"

build docker image (dry run):
  image: docker:dind
  stage: container
  tags: ["docker"]
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: on_success
    - when: never
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    # See https://github.com/docker-library/docker/pull/166
    DOCKER_TLS_CERTDIR: ""
  services:
    - name: docker:dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
  script:
    - sh build-all.sh
    - cd server/container
    - sh build.sh

build docker image:
  image: docker:dind
  stage: container
  tags: ["docker"]
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: on_success
    - when: never
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    # See https://github.com/docker-library/docker/pull/166
    DOCKER_TLS_CERTDIR: ""
  services:
    - name: docker:dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
  script:
    - cd server/container
    - sh build.sh
    - docker tag leya:local registry.code-better.it/leya/leya-print
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
    - docker push registry.code-better.it/leya/leya-print
