image:
  file: .gitpod.Dockerfile

tasks:
  - name: Rest-Server
    before: cd server/rest
    init: npm i & npx playwright install chrome
    command: npm run single
  
  - name: Designer
    before: cd web/designer
    init: npm i
    command: npm start
