image:
  file: .gitpod.Dockerfile

ports:
  - port: 3333
    visibility: public
    name: Templates
    onOpen: ignore
  - port: 6000
    visibility: public
    name: Pdf-Service
    onOpen: ignore
  - port: 6001
    visibility: public
    name: Tpl-Service
    onOpen: ignore
  - port: 6004
    visibility: public
    name: Auth-Service
    onOpen: ignore
  - port: 6002
    visibility: public
    name: Designer
    onOpen: ignore
  - port: 6003
    visibility: public
    name: Print
    onOpen: ignore

tasks:
  - name: Pre-Build
    init: |
      bash build-all.sh
